require 'spec_helper'
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UsersController, type: :controller do
  before(:each) do
    @user = FactoryGirl.build(:user)
    @new_user = FactoryGirl.build(:user)
  end
  after(:each) do
    if !@user.destroyed?
      @user.destroy
    end
  end
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      first_name: @user.first_name,
      last_name: @user.last_name,
      email: @user.email,
      password: @user.password
    }
  }

  let(:new_attributes) {
    {
      first_name: @new_user.first_name,
      last_name: @new_user.last_name,
      email: @new_user.email,
      password: @new_user.password
    }
  }

  let(:invalid_attributes) {
    {
      first_name: @user.first_name,
      email: @new_user.email,
      password: @user.password
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }
=begin
  ## ACCESS TO USERS INDEX PAGE IS NOT AVAILABLE
  describe "GET #index" do
    it "assigns all users as @users" do
      user = User.create! valid_attributes
      post :authenticate, {email: @user.email, password: @user.password}
      get :index, {}, valid_session
      expect(assigns(:users)).to eq([user])
    end
  end
=end

  describe "GET #show" do
    it "assigns the requested user as @user" do
      user = User.create! valid_attributes
      post :authenticate, {email: @user.email, password: @user.password}
      get :show, {:id => user.to_param}, valid_session
      expect(assigns(:user)).to eq(user)
    end
  end

  describe "GET #new" do
    it "assigns a new user as @user" do
      get :new, {}, valid_session
      expect(assigns(:user)).to be_a_new(User)
    end
  end

  describe "GET #edit" do
    it "assigns the requested user as @user" do
      user = User.create! valid_attributes
      post :authenticate, {email: @user.email, password: @user.password}
      get :edit, {:id => user.to_param}, valid_session
      expect(assigns(:user)).to eq(user)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, {:user => valid_attributes}, valid_session
        }.to change(User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, {:user => valid_attributes}, valid_session
        expect(assigns(:user)).to be_a(User)
        expect(assigns(:user)).to be_persisted
      end

      it "redirects to the created user" do
        post :create, {:user => valid_attributes}, valid_session
        expect(response).to redirect_to(User.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        post :create, {:user => invalid_attributes}, valid_session
        expect(assigns(:user)).to be_a_new(User)
      end

      it "re-renders the 'new' template" do
        post :create, {:user => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      it "updates the requested user" do
        user = User.create! valid_attributes
        post :authenticate, {email: @user.email, password: @user.password}
        put :update, {:id => user.to_param, :user => new_attributes}, valid_session
        user.reload
        #skip("Add assertions for updated state")
      end

      it "assigns the requested user as @user" do
        user = User.create! valid_attributes
        post :authenticate, {email: @user.email, password: @user.password}
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
        expect(assigns(:user)).to eq(user)
      end

      it "redirects to the user" do
        user = User.create! valid_attributes
        post :authenticate, {email: @user.email, password: @user.password}
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
        expect(response).to redirect_to(user)
      end
    end

    context "with invalid params" do
      it "assigns the user as @user" do
        user = User.create! valid_attributes
        post :authenticate, {email: @user.email, password: @user.password}
        put :update, {:id => user.to_param, :user => invalid_attributes}, valid_session
        expect(assigns(:user)).to eq(user)
      end

      it "re-renders the 'edit' template" do
        user = User.create! valid_attributes
        post :authenticate, {email: @user.email, password: @user.password}
        put :update, {:id => user.to_param, :user => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user" do
      user = User.create! valid_attributes
      post :authenticate, {email: @user.email, password: @user.password}
      expect {
        delete :destroy, {:id => user.to_param}, valid_session
      }.to change(User, :count).by(-1)
    end

    it "redirects to the users list" do
      user = User.create! valid_attributes
      post :authenticate, {email: @user.email, password: @user.password}
      delete :destroy, {:id => user.to_param}, valid_session
      expect(response).to redirect_to(users_url)
    end
  end

  describe "POST login" do
=begin
    before(:all) do
      @user = User.create(first_name: "Skillcrush", last_name: "Coder", email: "coder@skillcrush.com", password: "secret")
      @valid_user_hash = {email: @user.email, password: @user.password}
      @invalid_user_hash = {email: "", password: ""}
    end

    after(:all) do
      if !@user.destroyed?
        @user.destroy
      end
    end
=end

    it "redirects to the show view if params valid" do
      @user = User.create! valid_attributes
      @valid_user_hash = valid_attributes
      post :authenticate, @valid_user_hash
      expect(response).to redirect_to("/users/#{@user.id}")
    end

    it "populates @valid_user if params valid" do
      @user = User.create! valid_attributes
      @valid_user_hash = valid_attributes
      post :authenticate, @valid_user_hash
      expect(assigns[:valid_user].first_name).to eq(@user.first_name)
      expect(response).not_to render_template(:login)
    end

    it "renders the login view if params invalid" do
      @invalid_user_hash = invalid_attributes
      post :authenticate, @invalid_user_hash
      expect(response).to render_template(:login)
    end

    it "populates the @errors variable if params invalid" do
      @invalid_user_hash = invalid_attributes
      post :authenticate, @invalid_user_hash
      expect(assigns[:errors]).not_to be(nil)
    end
  end
end
